analyze_user_profile_task:
  description: >
    Carefully analyze the user profile provided: {user_profile}
    Extract and categorize all skills, expertise, education, and experience.
    Create a structured profile of the user's capabilities with proficiency levels where possible.
  expected_output: >
    A structured analysis of the user's skills, expertise, and qualifications organized by categories
    (technical skills, soft skills, education, experience, etc.) with proficiency levels indicated where possible.
  agent: skill_analyzer

analyze_requirements_task:
  description: >
    Thoroughly analyze the job/project requirements provided: {job_requirements}
    Extract all required skills, qualifications, experiences, and expectations.
    Categorize them by importance (must-have, preferred, nice-to-have).
  expected_output: >
    A structured analysis of the job requirements organized by categories and importance levels.
  agent: requirement_analyst

perform_gap_analysis_task:
  description: >
    Using the user profile analysis and job requirement analysis, perform a comprehensive
    comparison to identify:
    1. Skills/qualifications the user possesses that match the requirements
    2. Skills/qualifications the user lacks or needs improvement on
    3. User strengths that exceed requirements or provide additional value
    Prioritize the gaps based on importance to the job requirements.
  expected_output: >
    A detailed comparison report with:
    - Matching skills and qualifications
    - Skills gaps with improvement recommendations
    - Unique strengths and competitive advantages
    - Overall fit assessment and prioritized action plan
    Formatted as markdown without '```'
  agent: comparison_specialist
  depends_on: [analyze_user_profile_task, analyze_requirements_task]

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
